import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BridgeSDK, Event } from "@rome/bridgesdk";
import { useEffect, useState } from "react";
import Script from "next/script";

const msg: Event = {
  type: "EVENT_ROME_WIDGET_CLOSE",
  timestamp: 12312,
  broadcast: false,
  payload: undefined,
};

const Home: NextPage = () => {
  const [bus, setBus] = useState<BridgeSDK>();
  useEffect(() => {
    const initialize = async () => {
      const bus = await BridgeSDK.init("sherpa");
      console.log(bus);
      const msg: Event = {
        type: "EVENT_ROME_WIDGET_CLOSE",
        timestamp: 12312,
        broadcast: false,
        payload: undefined,
      };
      console.log("sending");
      setBus(bus);
    };
    initialize();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Script
          strategy="beforeInteractive"
          src="https://cdn.jsdelivr.net/npm/rxjs@6.6.3/bundles/rxjs.umd.min.js"
        ></Script>

        <button
          onClick={() => {
            bus.sendRequest({ request: msg });
          }}
        >
          Send Request
        </button>
        <button onClick={() => bus?.sendMessage({ message: msg })}>
          Send Message
        </button>
      </main>
    </div>
  );
};

export default Home;
